name: app2310020097
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # CORE
  get: ^4.6.5
  http: ^1.1.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  
  # IMAGE PICKER
  image_picker: ^0.8.7+4
  
  # URL LAUNCHER
  url_launcher: ^6.1.14
  
  # PATH PROVIDER (untuk akses file) - HAPUS DUPLIKAT
  path_provider: ^2.1.0

  pdf: ^3.10.0
  printing: ^5.11.0

  file_saver: ^0.1.1 

  # IMAGE CACHE
  cached_network_image: ^3.2.3

  # DOWNLOAD FEATURES
  permission_handler: ^11.0.1  # Untuk permission storage
  dio: ^5.4.0                  # Untuk download file
  open_file: ^3.3.2 
  
  path: ^1.8.3           # Untuk membuka file setelah didownload

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true